/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.*;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Event;
import java.awt.FocusTraversalPolicy;
import javax.swing.InputMap;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author josei
 */
public class PrincipalLogin extends javax.swing.JFrame {
    
    //Variables que serviran para obtener las coordenadas del mouse (esta se aplicará para mover las ventanas)
    int xMouse, yMouse;
    
    ControladorMetodos controladorMetodos = new ControladorMetodos();
    
    /**
     * Creates new form PrincipalLogin
     */
    public PrincipalLogin() {
        initComponents();
        
        setLocationRelativeTo(null); //ventana en medio de la pantalla
        
        //se inhabilita la opción depegar (Ctrl + v ó Shift + Insert)
        inhabilitarPegar(Fondo);
        
        //se inhabilita la opción de tabular (Tab)
        this.getContentPane().setFocusTraversalPolicyProvider(true);
        this.getContentPane().setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getLastComponent(Container aContainer) {
                    // TODO Auto-generated method stub
                    return null;
            }

            @Override
            public Component getFirstComponent(Container aContainer) {
                    return null;
            }
            @Override
            public Component getDefaultComponent(Container aContainer) {
                    return null;
            }

            @Override
            public Component getComponentBefore(Container aContainer,
                            Component aComponent) {
                    // TODO Auto-generated method stub
                    return null;
            }

            @Override
            public Component getComponentAfter(Container aContainer,
                            Component aComponent) {
                    // TODO Auto-generated method stub
                    return null;
            }
        });
        
    }
    
    private void inhabilitarPegar(Container contenedor){
        Component [] componentes = contenedor.getComponents();
        for (int i = 0; i < componentes.length; i++) {
            if (componentes [i] instanceof JTextField){
                InputMap map = ((JTextField)componentes[i]).getInputMap();
                map.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
                map.put(KeyStroke.getKeyStroke(KeyEvent.VK_INSERT, Event.SHIFT_MASK), "null");
            }
            else
                if (componentes [i] instanceof Container)
                    inhabilitarPegar((Container)componentes [i]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JTextField();
        passwordUsuario = new javax.swing.JPasswordField();
        PanelBtn = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelCerrar = new javax.swing.JPanel();
        cerrarLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        headerLogin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuario.setBackground(new java.awt.Color(244, 236, 252));
        nombreUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 11)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        nombreUsuario.setText("Ingrese nombre de usuario");
        nombreUsuario.setBorder(null);
        nombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioMousePressed(evt);
            }
        });
        nombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreUsuarioKeyTyped(evt);
            }
        });
        Fondo.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 230, 25));

        passwordUsuario.setBackground(new java.awt.Color(244, 236, 252));
        passwordUsuario.setForeground(new java.awt.Color(204, 204, 204));
        passwordUsuario.setText("********");
        passwordUsuario.setBorder(null);
        passwordUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordUsuarioMousePressed(evt);
            }
        });
        passwordUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordUsuarioKeyTyped(evt);
            }
        });
        Fondo.add(passwordUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 230, 20));

        PanelBtn.setBackground(new java.awt.Color(255, 255, 255));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_Btn/btnLogContNS.png"))); // NOI18N
        btnContinuar.setBorder(null);
        btnContinuar.setBorderPainted(false);
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.setFocusPainted(false);
        btnContinuar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_Btn/btnLogContNS.png"))); // NOI18N
        btnContinuar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_Btn/btnLogContS.png"))); // NOI18N
        btnContinuar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnContinuar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnLayout = new javax.swing.GroupLayout(PanelBtn);
        PanelBtn.setLayout(PanelBtnLayout);
        PanelBtnLayout.setHorizontalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addComponent(btnContinuar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelBtnLayout.setVerticalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addComponent(btnContinuar)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        Fondo.add(PanelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 290, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 20));

        panelCerrar.setBackground(new java.awt.Color(255, 255, 255));

        cerrarLogin.setBackground(new java.awt.Color(255, 255, 255));
        cerrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_Iconos/IconCerrar.png"))); // NOI18N
        cerrarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCerrarLayout = new javax.swing.GroupLayout(panelCerrar);
        panelCerrar.setLayout(panelCerrarLayout);
        panelCerrarLayout.setHorizontalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarLayout.createSequentialGroup()
                .addComponent(cerrarLogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCerrarLayout.setVerticalGroup(
            panelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarLayout.createSequentialGroup()
                .addComponent(cerrarLogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Fondo.add(panelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 40, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen_Fondos/FondoLogin.png"))); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        headerLogin.setBackground(new java.awt.Color(255, 255, 255));
        headerLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerLoginMouseDragged(evt);
            }
        });
        headerLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerLoginMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLoginLayout = new javax.swing.GroupLayout(headerLogin);
        headerLogin.setLayout(headerLoginLayout);
        headerLoginLayout.setHorizontalGroup(
            headerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        headerLoginLayout.setVerticalGroup(
            headerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Fondo.add(headerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLoginMousePressed
        //se asignan las coordenadas (del mouse en la ventana)
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerLoginMousePressed

    private void headerLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLoginMouseDragged
        //se asignan las coordenadas del mouse en pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //se restan los valores para obtener el resultado de mover la ventana
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerLoginMouseDragged

    private void cerrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarLoginMouseClicked

    private void nombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioMousePressed
        //Este tipo de evento es para visualizar un texto en los campos cuando 
        //no tienen nada escrito
        if(nombreUsuario.getText().equals("Ingrese nombre de usuario")){
            nombreUsuario.setText("");
            nombreUsuario.setForeground(Color.black);
        }
        if(String.valueOf(passwordUsuario.getPassword()).isEmpty()){
            passwordUsuario.setText("********");
            passwordUsuario.setForeground(new java.awt.Color(204,204,204));
        }
    }//GEN-LAST:event_nombreUsuarioMousePressed

    private void passwordUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordUsuarioMousePressed
        if(String.valueOf(passwordUsuario.getPassword()).equals("********")){
            passwordUsuario.setText("");
            passwordUsuario.setForeground(Color.black);
        }
        if(nombreUsuario.getText().isEmpty()){
            nombreUsuario.setForeground(new java.awt.Color(204,204,204));
            nombreUsuario.setText("Ingrese nombre de usuario");            
        }
    }//GEN-LAST:event_passwordUsuarioMousePressed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String usuario = nombreUsuario.getText();
        char[] arrayC = passwordUsuario.getPassword();
        String pass = new String(arrayC);
        //se verifica que el usuario y contraseña coincidan en la BD
        //y se obtiene el área de ese usuario
        String resultado = controladorMetodos.buscarUsuario(usuario, pass);
        
        if (resultado.equals("Ventas")){ //Si el área es de Ventas
            AreaVentas av = new AreaVentas();
            av.setVisible(true);
            this.dispose();
        }else{
            if(resultado.equals("Compras")){ //Si el área es de Compras
                AreaCompras ac = new AreaCompras();
                ac.setVisible(true);
                this.dispose();
            }else{
                if(resultado.equals("Finanzas")){ //Si el área es de Finanzas
                    AreaFinanzas af = new AreaFinanzas();
                    af.setVisible(true);
                    this.dispose();
                }if(resultado.isEmpty()){ //Si no coincide con lo anterior se muestra mensaje de error
                    AlertaWarning salir = new AlertaWarning(this, true);
                    salir.mensaje.setText("Valores inválidos.");
                    salir.setVisible(true);
                    
                    nombreUsuario.setForeground(new java.awt.Color(204,204,204));
                    nombreUsuario.setText("Ingrese nombre de usuario");
                    passwordUsuario.setText("********");
                    passwordUsuario.setForeground(new java.awt.Color(204,204,204));
                }
            }
        }
        
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void nombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreUsuarioKeyTyped
        if(this.nombreUsuario.getText().length() >= 30)
            evt.consume();
    }//GEN-LAST:event_nombreUsuarioKeyTyped

    private void passwordUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordUsuarioKeyTyped
        if(this.passwordUsuario.getText().length() >= 20)
            evt.consume();
    }//GEN-LAST:event_passwordUsuarioKeyTyped

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel PanelBtn;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel cerrarLogin;
    private javax.swing.JPanel headerLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JPanel panelCerrar;
    private javax.swing.JPasswordField passwordUsuario;
    // End of variables declaration//GEN-END:variables
}
